### PR TITLE
Version 0.2.0b0

### PR DESCRIPTION
**Pull request by whiteluna**
- Add Rack-aware load balancing
- Improve perfomance for bind date/datetime
- When execute statement with `native_types=True` returns same as `SELECT JSON ...`
- Add `parameters` for PreparedStatement.bind function
- Added the ability to asynchronously iterate over the result. For Example:
```python
 prepared = await session.create_prepared("SELECT id, value FROM test WHERE value>:value")
 statement = prepared.bind(parameters={value: 0}, page_size=10)
 async for row in statement:
     ...
```

### CODE REVIEW

**Comment by whiteluna** [comment]
@pfreixes ping

**Comment by pfreixes** [comment]
Time for a new version?

**Comment by whiteluna** [comment]
@pfreixes thanks, build please

**Comment by pfreixes** [comment]
Seems that CI is failing, wondering if could be something related to your PR https://github.com/acsylla/acsylla/actions/runs/6026811354/job/16351917703 ? there is a segfault happening always in the same point, could you take a look?

**Pull request merged**
